### ISSUE TITLE
How do I center this?

### ISSUE THREAD

**Issue by windcloak** [Gbuomprisco/ngx-content-loading#16]
I've tried text-center and d-flex justify-content-center and I can't seem to center this. I've also tried putting the whole thing into a div and centering the div, but it didn't work either. How do I center it?

```
<ngx-content-loading [height]="300" class="text-muted text-center">
<b before-svg><h3>loading...</h3></b>
<svg:g ngx-bullet-list-preset></svg:g>
</ngx-content-loading>
```

**Comment by Gbuomprisco** [comment]
Hi, you should probably try to assign a width (ex .auto) and then on the hist component the following css:
```
ngx-content-loading {
  display: flex;
  justify-content: center;
}
```

Sorry but I haven't updated this in a long time, it may not work as you expect

**Comment by windcloak** [comment]
I was able to fix this by making the svg width the same width as the ngx-loading-content width. It seems like it won't work with a predefined one though.

`  <ngx-content-loading
  [speed]="'1500ms'"
  [width]="300"
  [height]="300"
  [primaryColor]="'#eee'"
  [secondaryColor]="'#fff'">
	<svg:g ngx-rect width="300" height="10" y="10" x="0" rx="5" ry="5"></svg:g>
	<svg:g ngx-rect width="300" height="10" y="40" x="0" rx="5" ry="5"></svg:g>
	<svg:g ngx-rect width="300" height="10" y="70" x="0" rx="5" ry="5"></svg:g>
</ngx-content-loading>`
