### ISSUE TITLE
Angular 5.x | ERROR TypeError: Cannot read property 'speed' of undefined

### ISSUE THREAD

**Issue by kapiladiyecha** [Gbuomprisco/ngx-content-loading#3]
This error occurred **Without AoT** [During `ng serve`]

Compiled without errors, but IDE shows error:
![image](https://user-images.githubusercontent.com/6995248/36957076-e3889816-206c-11e8-8915-ac04ac0f3910.png)

When jumped to the page, where the content placeholder placed, it throws the following error:
![image](https://user-images.githubusercontent.com/6995248/36957068-d370f2d4-206c-11e8-86f2-fec485cfcea9.png)

**Versions using:**
```
"ngx-content-loading": "0.0.9-rc1"
"@angular/core": "^5.2.6"
"@angular/cli": "^1.7.1"

```

**Comment by Gbuomprisco** [comment]
Are you sure you're importing the module?

**Comment by kapiladiyecha** [comment]
Yes, I'm sure. I've imported module, the first error can be fixed by importing `CUSTOM_ELEMENTS_SCHEMA`.

Ref: https://stackoverflow.com/questions/39428132/custom-elements-schema-added-to-ngmodule-schemas-still-showing-error

But, for the second error, the reason is that not able to get `content` in the package, that's why it's throwing `Can not read property 'speed' of undefined`.

**Comment by Gbuomprisco** [comment]
Can you post an online demo for this

**Comment by kapiladiyecha** [comment]
Thanks for the quick response.

Here is the demo with the same error:
**Plunker**: [https://embed.plnkr.co/TqWCp8HWQ2cm8urnaoPB/](https://embed.plnkr.co/TqWCp8HWQ2cm8urnaoPB/) 
[_you can open the console and check error_]
![image](https://user-images.githubusercontent.com/6995248/36969919-ca1f89a4-20a1-11e8-95e0-885996fec16d.png)


**Zip file with a fresh simple `angular-cli` project**: [ngx-content-loading-demo.zip](https://github.com/Gbuomprisco/ngx-content-loading/files/1780399/ngx-content-loading-demo.zip)

**Comment by sippaprut** [comment]
I got same error on angular 4

**Comment by Gbuomprisco** [comment]
Can you try v 0.0.8? It will still not work with AOT, see the other issue open in this repository for details

**Comment by kapiladiyecha** [comment]
Sure, but where can I get v 0.0.8?

![image](https://user-images.githubusercontent.com/6995248/37017979-980878a2-214d-11e8-86df-f1b928132653.png)

**Comment by kapiladiyecha** [comment]
Yes @Gbuomprisco, it's working with **v 0.0.8**.
Thanks for such a nice plugin.
Waiting for AoT support. I'll try to fix bug with the current version and will update here.

**Comment by Gbuomprisco** [comment]
I'm awaiting for news on that as well :)

**Comment by kapiladiyecha** [comment]
Hi @Gbuomprisco ,

I reopened this issue regarding `Cannot read property 'speed' of undefined` issue.
As #2 (AoT support) fixed. Can it be fixed in the latest version?

Thanks

**Comment by Gbuomprisco** [comment]
Can you please post the component controller code? From the error content is undefined

**Comment by kapiladiyecha** [comment]
I've already uploaded the code.

You can check this: Plunker: https://embed.plnkr.co/TqWCp8HWQ2cm8urnaoPB/

Zip file with a fresh simple angular-cli project:

[ngx-content-loading-demo.zip](https://github.com/Gbuomprisco/ngx-content-loading/files/1969512/ngx-content-loading-demo.zip)

**Comment by Gbuomprisco** [comment]
I wanted to check the property "content". It seems undefined. "Cannot read property 'speed' of undefined". Which in the tempate is referenced by content.

**Comment by kapiladiyecha** [comment]
If you see this image, Line number 17, 
here `speed` property used in the ngx-content-loading, which is causing this problem.

![image](https://user-images.githubusercontent.com/6995248/36957068-d370f2d4-206c-11e8-86f2-fec485cfcea9.png)

**Comment by Gbuomprisco** [comment]
Can you show me what content is?

**Comment by hatem20** [comment]
@kapiladiyecha you solved the problem?

**Comment by kapiladiyecha** [comment]
No @hatem20 ,  it is not solved yet.

@Gbuomprisco , `content`  is coming from this plugin, I just followed steps to import this, and just tried predefined placeholders without any other custom code.

And it is throwing the same error.

I'm not able to understand what else I can share, if you create the fresh project with angular-cli, angular 5.x you may face the same issue.

I already have attached one sample project in previous comment.

Thanks

**Comment by hatem20** [comment]
thanks alot @kapiladiyecha 
@Gbuomprisco i think this issue should not be closed

**Comment by kapiladiyecha** [comment]
@Gbuomprisco Can you please reopen this issue?
