### ISSUE TITLE
[Reopened] Angular 5.x | ERROR TypeError: Cannot read property 'speed' of undefined

### ISSUE THREAD

**Issue by kapiladiyecha** [Gbuomprisco/ngx-content-loading#6]
I'm submitting the bug again because I'm not able to reopen #3  and it is not resolved yet.

It happens with the fresh project with angular-cli.

Please find attached plunkr sample.
https://embed.plnkr.co/TqWCp8HWQ2cm8urnaoPB/

Thanks

**Comment by evgshk** [comment]
I have the same error.

**Comment by FilipLukac** [comment]
mee too

**Comment by Gbuomprisco** [comment]
Hi guys, can you try v 0.1.1?

**Comment by FilipLukac** [comment]
Hello, it works, but Animation is disabled right now :\ Only appears black presets (no animation appears)

**Comment by Gbuomprisco** [comment]
Hi, I think I found the issue. Can you try 0.1.2?

**Comment by FilipLukac** [comment]
Thank you so much, fixed right now ! 👍

**Comment by kapiladiyecha** [comment]
Thanks a lot man @Gbuomprisco. It is working now :)
